### PR TITLE
Responsive hamburger bar + sign in sign up page

### PR DESCRIPTION
**Pull request by developer208**
Screenshot (372)
Screenshot (373)

### CODE REVIEW

**Comment by Buddhad** [comment]
resolve the conflicts then its ready to merged

**Comment by developer208** [comment]
there are no conflicts then why vercel deployment failed

**Comment by developer208** [comment]
@Buddhad  what about this deployment error ?

**Comment by Buddhad** [comment]
> @Buddhad what about this deployment error ?

Pull all the code then refine the code it will work

**Comment by developer208** [comment]
@Buddhad  solved . thanks

**Comment by Buddhad** [comment]
> 



> @Buddhad solved . thanks

Login system and google Sign in not working. I have tried to register and login but not working.

**Comment by Buddhad** [comment]
**This is not fixed.**
image

**Comment by Buddhad** [comment]
hey buddy try to use **firebase** for the login system.

**Comment by developer208** [comment]
Okay I'll try .

**Pull request closed without merging**
